InventoryMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('staff/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ItemSearchListView,
)

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('products/',ProductListView.as_view(), name="productslist"),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('new-product/', ProductCreateView.as_view(), name='product-create'),
    path('product/<slug:slug>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('product/<slug:slug>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    path('search/',ItemSearchListView.as_view(), name="item_search_list_view"),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.text import slugify
from django_extensions.db.fields import AutoSlugField


STATUS_CHOICES = [
    ('INA', 'Inactive'),
    ('A', 'Active'),
    ('OL', 'On_leave')
]

ROLE_CHOICES = [
    ('OP', 'Operative'),
    ('EX', 'Executive'),
    ('AD', 'Admin')
]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = AutoSlugField(unique=True, verbose_name=('Account ID'), populate_from='email')
    profile_picture = ProcessedImageField(default='profile_pics/default.jpg', upload_to='profile_pics', format='JPEG',
                                processors = [ResizeToFill(150,150)],
                                options={ 'quality': 100})
    telephone = PhoneNumberField(null=True,blank=True)
    email = models.CharField(max_length=150, blank=True, null=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=12, blank=False, null=False, default='INA')
    role = models.CharField(choices=ROLE_CHOICES, max_length=12, blank=True, null=True)

    @property
    def imageURL(self):
        try:
            url= self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return f'{self.user.username} Profile'

    class Meta:
        ordering = ["slug"]

store/models.py
"""
Module: models.py

Contains Django models for handling categories, items, and deliveries.

This module defines the following classes:
- Category: Represents a category for items.
- Item: Represents an item in the inventory.
- Delivery: Represents a delivery of an item to a customer.

Each class provides specific fields and methods for handling related data.
"""
from django.db import models
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import Sum
from functools import cached_property 

class Item(models.Model):
    """
    Represents an item in the inventory.
    """
    slug = AutoSlugField(unique=True , populate_from='name')
    name = models.CharField(max_length=500, blank=False, null=False)
    barcode = models.CharField(max_length=20, unique=True)
    expiry_date = models.DateField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        """
        String representation of the item.
        """
        return f"{self.barcode}: Count:{self.inventory_count} :{self.name}"

    def get_absolute_url(self):
        """
        Returns the absolute URL for an item detail view.
        """
        return reverse('item-detail', kwargs={'slug': self.slug})

    @cached_property
    def inventory_count(self):
        last = self.reports.order_by('-transaction_date').first()
        if last:
            return last.ending_inventory or 0
        return 0
            

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Products"



# Script to populate the Item model
def populate_item():
    import json
    from datetime import datetime

    # Specify the path to your JSON file
    json_file_path = "../products.json"

    # Read the JSON data from the file
    with open(json_file_path, "r") as f:
        data = json.load(f)
    for item_data in data:
        if item_data["barcode"]:  # Check if barcode is not empty
            # If expiry_date is empty, set it to None
            # If expiry_date is "No Expiry", set it to None
            exp_date = item_data["expiry_date"]
            expiry_date = None if (exp_date == "No Expiry") or (exp_date == "") or (not exp_date)  else datetime.strptime(item_data["expiry_date"], "%d-%b-%y")


            # Create or update the Item
            item, created = Item.objects.update_or_create(
                barcode=item_data["barcode"],
                defaults={
                    "name": item_data["name"],
                    "expiry_date": expiry_date
                }
            )

store/forms.py
from django import forms
from django.forms import ModelForm
from .models import Item

class ProductForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        widgets = {
            'expiry_date': forms.TextInput(     
                attrs={'type': 'date'} 
            )
        }

store/views.py
"""
Module: store.views

Contains Django views for managing items, profiles, and deliveries in the store application.

Classes handle product listing, creation, updating, deletion, and delivery management.
The module integrates with Django's authentication and querying functionalities.
"""
import operator
from functools import reduce
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django_tables2 import SingleTableView
import django_tables2 as tables
from django_tables2.export.views import ExportMixin
from django_tables2.export.export import TableExport
from django.db.models import Q, Count, Sum, Avg
from django.views.generic.edit import FormMixin

from accounts.models import Profile
from transactions.models import Sale
from .models import Item
from .forms import ProductForm
from .tables import ItemTable

@login_required
def dashboard(request):
    """
    View function to render the dashboard with item and profile data.

    Args:
    - request: HttpRequest object.

    Returns:
    - Rendered template with dashboard data.
    """
    profiles =  Profile.objects.all()
    items = Item.objects.all()
    total_items = Item.objects.all().aggregate(Count('id')).get('id__count', 0.00)
    items_count = items.count()
    profiles_count = profiles.count()

    #profile pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(profiles, 3)
    try:
        profiles = paginator.page(page)
    except PageNotAnInteger:
        profiles = paginator.page(1)
    except EmptyPage:
        profiles = paginator.page(paginator.num_pages)

    #items pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(items, 4)
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    context = {
        'items': items,
        'profiles' : profiles,
        'profiles_count': profiles_count,
        'items_count': items_count,
        'total_items': total_items,
        'sales': Sale.objects.aggregate(Sum('sales')).get('sales__sum', 0) or 0
    }
    return render(request, 'store/dashboard.html', context)
class ProductListView(LoginRequiredMixin, ExportMixin, tables.SingleTableView):
    """
    View class to display a list of products.

    Attributes:
    - model: The model associated with the view.
    - table_class: The table class used for rendering.
    - template_name: The HTML template used for rendering the view.
    - context_object_name: The variable name for the context object.
    - paginate_by: Number of items per page for pagination.
    """
    model = Item
    table_class = ItemTable
    template_name = 'store/productslist.html'
    context_object_name = 'items'
    paginate_by = 20
    SingleTableView.table_pagination = False

class ItemSearchListView(ProductListView):
    """
    View class to search and display a filtered list of items.

    Attributes:
    - paginate_by: Number of items per page for pagination.
    """
    paginate_by = 10

    def get_queryset(self):
        result = super(ItemSearchListView, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(name__icontains=q) for q in query_list))
            )
        return result

class ProductDetailView(LoginRequiredMixin, FormMixin, DetailView):
    """
    View class to display detailed information about a product.

    Attributes:
    - model: The model associated with the view.
    - template_name: The HTML template used for rendering the view.
    """
    model = Item
    template_name = 'store/productdetail.html'

    def get_success_url(self):
        return reverse('product-detail', kwargs={'slug': self.object.slug})

class ProductCreateView(LoginRequiredMixin, CreateView):
    """
    View class to create a new product.

    Attributes:
    - model: The model associated with the view.
    - template_name: The HTML template used for rendering the view.
    - form_class: The form class used for data input.
    - success_url: The URL to redirect to upon successful form submission.
    """
    model = Item
    template_name = 'store/productcreate.html'
    form_class = ProductForm
    success_url = '/products'

    def test_func(self):
        return True

class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    View class to update product information.

    Attributes:
    - model: The model associated with the view.
    - template_name: The HTML template used for rendering the view.
    - fields: The fields to be updated.
    - success_url: The URL to redirect to upon successful form submission.
    """
    model = Item
    template_name = 'store/productupdate.html'
    form_class = ProductForm
    success_url = '/products'

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        else:
            return False


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    View class to delete a product.

    Attributes:
    - model: The model associated with the view.
    - template_name: The HTML template used for rendering the view.
    - success_url: The URL to redirect to upon successful deletion.
    """
    model = Item
    template_name = 'store/productdelete.html'
    success_url = '/products'


    def test_func(self):
        if self.request.user.is_superuser:
            return True
        else:
            return False

store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}" type="text/css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://unpkg.com/@webpixels/css@1.1.5/dist/index.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
        <script defer src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

        <title>Inventory Management System: {% block title %} {% endblock title %}</title>

    </head>
    <body>
      <style>
        .paginator {
          display: flex;
          justify-content: center;
        }
      </style>
        {% include "store/sidebar.html" %}
        <section id="wrapper">
            <nav class="navbar navbar-expand-md bg-success">
                <div class="container-fluid mx-2">
                  <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#toggle-navbar" aria-controls="toggle-navbar" aria-expanded="false" aria-label="Toggle navigation">
                      <i class="fa fa-bars text-white"></i>
                    </button>
                    <a class="navbar-brand" style="font-size: 20px;" href="{% url 'dashboard' %}">Inventory<span class="text-warning">ms</span></a>
                  </div>
                  <div class="collapse navbar-collapse" id="toggle-navbar">
                    <ul class="navbar-nav ms-auto">
                      {% comment %} <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-bell"></i><span>98</span></a>
                      </li> {% endcomment %}
                      {% comment %} <li class="nav-item">
                        <a class="nav-link" href="#">
                          <i data-show="show-side-navigation1" class="fa fa-bars show-side-btn"></i>
                        </a>
                      </li> {% endcomment %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'user-logout' %}">
                          <i data-show="show-side-navigation1" class="fa fa-sign-out show-side-btn"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </nav>
        {% block content%}

        {% endblock content%}
        </section>
        </div>
        <!-- Load jQuery before form.media -->
        <script type="text/javascript" src="{% static 'js/main.js'%}"></script>
        <script type="text/javascript" src="{% static 'js/dashboard.js'%}"></script>
        <script type="text/javascript" src="{% static 'fontawesome/js/all.js' %}" crossorigin="anonymous"></script>
    </body>
</html>

store/templates/store/charts.html
<!-- <div class="row">
    <div class="card shadow border-0 mb-7 col-md-6 col-lg-6">
        <div class="bg-white">
          <canvas id="myChart" style="width:100%;max-width:600px"></canvas>
            <script>
              var xValues = ["Office Supplies", "Pesonal care", "Clothing", "Technology"];
              var yValues = [102, 200, 120, 54];
              var barColors = [
                "#b91d47",
                "#00aba9",
                "#2b5797",
                "#e8c3b9",
              ];

              new Chart("myChart", {
                type: "pie",
                data: {
                  labels: xValues,
                  datasets: [{
                    backgroundColor: barColors,
                    data: yValues
                  }]
                },
                options: {
                  title: {
                    display: true,
                    text: "Products in stock Pie chart"
                  }
                }
              });
            </script>
        </div>
    </div>
    <div class="card shadow border-0 mb-7 col-md-6 col-lg-6">
      <small><b>demand supply curve</b></small>
      <canvas id="myChart4" style="width:100%;max-width:600px"></canvas>
        <script>
        var xValues = [50,60,70,80,90,100,110,120,130,140,150];
        var yValues = [7,8,8,9,9,9,10,11,14,14,15];

        new Chart("myChart4", {
          type: "line",
          data: {
            labels: xValues,
            datasets: [{
              fill: false,
              lineTension: 0,
              backgroundColor: "rgba(0,0,255,1.0)",
              borderColor: "rgba(0,0,255,0.1)",
              data: yValues
            }]
          },
          options: {
            legend: {display: false},
            scales: {
              yAxes: [{ticks: {min: 6, max:16}}],
            }
          }
        });
        </script>
    </div>
</div> -->

store/templates/store/dashboard.html
{% extends "store/base.html" %}{% load static %}{% block title %}Dashboard{%endblock title%}{% block content %}
<!-- Dashboard -->
<div class="d-flex flex-column flex-lg-row h-lg-full bg-surface-secondary">
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    <!-- Main content -->
    <div class="h-screen flex-grow-1 overflow-y-lg-auto">
        <!-- Main -->
        <main class="py-6 bg-surface-secondary">
            <div class="container-fluid">
                <!-- Card stats -->
                <div class="row g-6 mb-6">
                    <div class="col-xl-4 col-sm-6 col-12" id="products">
                        <a href="{%  url 'productslist' %}">
                        <div class="card shadow border-0">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <span class="h6 font-semibold text-muted text-sm d-block mb-2">Products</span>
                                        <span class="h3 font-bold mb-0">{{total_items}}</span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-tertiary text-white text-lg rounded-circle">
                                            <i class="fa fa-credit-card"></i>
                                        </div>
                                    </div>
                                </div>
                                <!-- <div class="mt-2 mb-0 text-sm">
                                    <span class="badge badge-pill bg-soft-success text-success me-2">
                                        <i class="fa fa-arrow-up me-1"></i>13%
                                    </span>
                                    <span class="text-nowrap text-xs text-muted">Since last month</span>
                                </div> -->
                            </div>
                        </div>
                        </a>
                    </div>

                    <div class="col-xl-4 col-sm-6 col-12" id="sales">
                        <a href="{% url 'saleslist' %}">
                            <div class="card shadow border-0">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <span class="h6 font-semibold text-muted text-sm d-block mb-2">Sales</span>
                                            <span class="h3 font-bold mb-0">{{ sales }}</span>
                                        </div>
                                        <div class="col-auto">
                                            <div class="icon icon-shape bg-warning text-white text-lg rounded-circle">
                                                <i class="fa fa-shopping-cart"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- <div class="mt-2 mb-0 text-sm">
                                        <span class="badge badge-pill bg-soft-success text-success me-2">
                                            <i class="fa fa-arrow-up me-1"></i>10%
                                        </span>
                                        <span class="text-nowrap text-xs text-muted">Since last month</span>
                                    </div> -->
                                </div>
                            </div>
                        </a>
                    </div>

                    <div class="col-xl-4 col-sm-6 col-12" id="profiles">
                        <a href="{% url 'profile_list' %}">
                            <div class="card shadow border-0">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <span class="h6 font-semibold text-muted text-sm d-block mb-2">Staff</span>
                                            <span class="h3 font-bold mb-0">{{profiles_count}}</span>
                                        </div>
                                        <div class="col-auto">
                                            <div class="icon icon-shape bg-primary text-white text-lg rounded-circle">
                                                <i class="fa-solid fa-people-group"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- <div class="mt-2 mb-0 text-sm">
                                        <span class="badge badge-pill bg-soft-success text-success me-2">
                                            <i class="fa fa-arrow-up me-1"></i>30%
                                        </span>
                                        <span class="text-nowrap text-xs text-muted">Since last month</span>
                                    </div> -->
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                {% include 'store/charts.html' %}
                <div class="row">
                    <div class="card shadow border-0 mb-7 col-md-6 col-lg-6">
                        <div class="card-header">
                            <h5 class="mb-0 font-bold">Products</h5>
                        </div>
                        <div class="table-responsive able-sm">
                            <table class="table table-hover table-nowrap">
                                <thead class="thead-light">
                                    <tr>
                                        <th scope="col">Product Name</th>
                                        <th scope="col">Inventory Count</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in items %}
                                    <tr>
                                        <td>
                                            {{item.name}}
                                        </td>
                                        <td>
                                            {{ item.inventory_count }}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="text-center">
                            <a class="btn btn-success btn-sm" href="{% url 'productslist' %}">View all</a>
                        </div>
                    </div>
                    <div class="card shadow border-0 mb-7 col-md-6 col-lg-6">
                        <div class="card-header">
                            <h5 class="mb-0 font-bold">Staff</h5>
                        </div>
                        <div class="table-responsive table-sm">
                            <table class="table table-hover table-nowrap">
                                <thead class="thead-light">
                                    <tr>
                                        <th scope="col">Profile Image</th>
                                        <th scope="col">username</th>
                                        <th scope="col">Phone Number</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Role</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for profile in profiles %}
                                    <tr>
                                        <td>
                                            <img alt="..." src="{{profile.profile_picture.url}}" class="avatar avatar-sm rounded-circle me-2">
                                        </td>
                                        <td>
                                            {{profile.user.username}}
                                        </td>
                                        <td>
                                        {{profile.telephone}}
                                        </td>
                                        <td>
                                            {% if profile.status == 'A' %}
                                                <span class="badge badge-pill bg-soft-success text-success me-2">
                                                    Active
                                                </span>
                                                {% elif profile.status == 'OL' %}
                                                <span class="badge badge-pill bg-soft-warning text-warning me-2">
                                                    On_leave
                                                </span>
                                                {% else %}
                                                <span class="badge badge-pill bg-soft-danger text-danger me-2">
                                                Inactive
                                            {% endif %}
                                        </td>
                                        <td class="text-end">
                                            {% if profile.role == 'AD' %}
                                                Admin
                                                {% elif profile.role == 'EX' %}
                                                Executive
                                                {% else %}
                                                Operative
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="text-center">
                            <a class="btn btn-success btn-sm" href="{% url 'profile_list' %}">View all</a>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</div>
{% endblock content %}

store/templates/store/productcreate.html
{% extends "store/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add product{%endblock title%}{% block content %}
<div class="col container p-5">
    <div class="row">
        <div class="col-md-3 col-lg-3"></div>
          <div class="col-md-6 col-lg-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <section class="section-bg" id="plans">
                    <fieldset class="form-group">
                        <header class="section-header">
                            <h1 class="text-success">Add product</h1>
                            <hr>
                        </header>
                        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
                        {{ form.media }}
                        {{form | crispy }}
                    </fieldset>
                </section>
                <div class="form-group mt-4 text-center">
                    <button class="btn btn-success" type="submit">Submit</button>
                </div>
            </form>
        </div>
        <div class="col-md-3 col-lg-3"></div>
    </div>
</div>
{% endblock content %}

store/templates/store/sidebar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<aside class="sidebar position-fixed top-0 left-0 overflow-auto h-100 float-left" id="show-side-navigation1">
    <i class="fa fa-bars close-aside d-md-none d-lg-none" data-close="show-side-navigation1"></i>
    <div class="sidebar-header d-flex justify-content-center align-items-center px-3 py-4">
      <a href="{% url 'user-profile' %}">
        <img
          class="rounded-pill img-fluid"
          id = "sidebar-img"
          width="65"
          src="{{request.user.profile.profile_picture.url}}"
          alt="">
        </a>
        <div class="ms-2">
          <h5 class="fs-6 mb-0 text-white">{{user.username}}{% if user.profile.role == 'AD' %} <i class="fa-solid fa-circle-check"></i>{% endif %}</h5>
          <span class="badge badge-pill bg-soft-success text-success me-2">
            {% if user.profile.role == 'AD' %}
              Admin
            {% elif user.profile.role == 'EX' %}
              Executive
            {% else %}
              Operative
        {% endif %}
          </span>
        </div>
    </div>
    <ul class="categories list-unstyled">
      <li>
        <i class="fa fa-home fa-fw"></i><a href="{% url 'dashboard' %}"> Dashboard</a>
      </li>
      <li class="">
        <i class="fa fa-folder"></i><a href="{% url 'productslist' %}"> Products</a>
      </li>
      <li>
        <i  class="fa fa-shopping-bag fa-fw"></i><a href="{% url 'saleslist' %}">Reports</a>
      </li>
      <li>
        <i class="fa-solid fa-people-group"></i><a href="{% url 'profile_list' %}"> Staff</a>
      </li>
      <li class="">
        <a class="btn btn-sm btn-danger" href="{% url 'user-logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
      </li>
    </ul>
  </aside>